// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: lang.jflex


 /*  Esta seção é copiada antes da declaração da classe do analisador léxico.
  *  É nesta seção que se deve incluir imports e declaração de pacotes.
  *  Neste exemplo não temos nada a incluir nesta seção.
  */
  package parsers;
import beaver.Symbol;
import beaver.Scanner;

  

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class LangLex extends Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1d00\1\u1e00"+
    "\1\u1f00\1\u2000\2\u2100\1\u2200\7\u2100\1\u2300\1\u2400\1\u2500"+
    "\1\u2100\1\u2600\1\u2700\2\u2100\31\u1100\1\u2800\121\u1100\1\u2900"+
    "\4\u1100\1\u2a00\1\u1100\1\u2b00\1\u2c00\1\u2d00\1\u2e00\1\u2f00"+
    "\1\u3000\53\u1100\1\u3100\10\u3200\31\u2100\1\u1100\1\u3300\1\u3400"+
    "\1\u1100\1\u3500\1\u3600\1\u3700\1\u3800\1\u2100\1\u3900\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u1100\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u2100\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u2100"+
    "\1\u5000\1\u5100\1\u5200\1\u2100\3\u1100\1\u5300\1\u5400\1\u5500"+
    "\12\u2100\4\u1100\1\u5600\17\u2100\2\u1100\1\u5700\41\u2100\2\u1100"+
    "\1\u5800\1\u5900\2\u2100\1\u5a00\1\u5b00\27\u1100\1\u5c00\2\u1100"+
    "\1\u5d00\45\u2100\1\u1100\1\u5e00\1\u5f00\11\u2100\1\u6000\27\u2100"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\11\u2100\1\u6500\1\u6600\5\u2100"+
    "\1\u6700\1\u6800\4\u2100\1\u6900\2\u2100\1\u6a00\16\u2100\246\u1100"+
    "\1\u6b00\20\u1100\1\u6c00\1\u6d00\25\u1100\1\u6e00\34\u1100\1\u6f00"+
    "\14\u2100\2\u1100\1\u7000\u0e05\u2100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\3\0\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\0\1\15\1\16\1\17\12\20\1\21\1\22"+
    "\1\23\1\24\1\25\2\0\32\26\1\27\1\0\1\30"+
    "\1\0\1\31\1\0\1\32\2\33\1\34\1\35\1\36"+
    "\2\33\1\37\2\33\1\40\1\33\1\41\1\33\1\42"+
    "\1\33\1\43\1\44\1\45\1\46\1\33\1\47\3\33"+
    "\1\50\1\51\1\52\7\0\1\3\44\0\1\33\12\0"+
    "\1\33\4\0\1\33\5\0\27\26\1\0\7\26\30\33"+
    "\1\0\10\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\2\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\2\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\2\26\1\33\1\26\1\33\1\26\3\33\2\26\1\33"+
    "\1\26\1\33\2\26\1\33\3\26\2\33\4\26\1\33"+
    "\2\26\1\33\3\26\3\33\2\26\1\33\2\26\1\33"+
    "\1\26\1\33\1\26\1\33\2\26\1\33\1\26\2\33"+
    "\1\26\1\33\2\26\1\33\3\26\1\33\1\26\1\33"+
    "\2\26\2\33\1\31\1\26\3\33\4\31\1\26\1\31"+
    "\1\33\1\26\1\31\1\33\1\26\1\31\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\2\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\2\33\1\26\1\31\1\33\1\26\1\33\3\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\7\33\2\26\1\33\2\26\2\33\1\26\1\33"+
    "\4\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\105\33\1\31\44\33\7\31\2\33\4\0\14\31"+
    "\16\0\5\33\7\0\1\31\1\0\1\31\126\0\1\53"+
    "\52\0\1\26\1\33\1\26\1\33\1\31\1\0\1\26"+
    "\1\33\2\0\4\33\1\0\1\26\6\0\1\26\1\0"+
    "\3\26\1\0\1\26\1\0\2\26\1\33\21\26\1\0"+
    "\11\26\43\33\1\26\2\33\3\26\3\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\5\33\1\26\1\33"+
    "\1\0\1\26\1\33\2\26\2\33\63\26\60\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\10\0\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\2\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\2\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\0\46\26"+
    "\2\0\1\31\6\0\51\33\107\0\33\31\4\0\4\31"+
    "\55\0\53\31\25\0\12\20\4\0\2\31\1\0\143\31"+
    "\1\0\1\31\17\0\2\31\7\0\2\31\12\20\3\31"+
    "\2\0\1\31\20\0\1\31\1\0\36\31\35\0\131\31"+
    "\13\0\1\31\16\0\12\20\41\31\11\0\2\31\4\0"+
    "\1\31\5\0\26\31\4\0\1\31\11\0\1\31\3\0"+
    "\1\31\27\0\31\31\7\0\13\31\65\0\25\31\1\0"+
    "\10\31\106\0\66\31\3\0\1\31\22\0\1\31\7\0"+
    "\12\31\4\0\12\20\1\0\20\31\4\0\10\31\2\0"+
    "\2\31\2\0\26\31\1\0\7\31\1\0\1\31\3\0"+
    "\4\31\3\0\1\31\20\0\1\31\15\0\2\31\1\0"+
    "\3\31\4\0\12\20\2\31\12\0\1\31\10\0\6\31"+
    "\4\0\2\31\2\0\26\31\1\0\7\31\1\0\2\31"+
    "\1\0\2\31\1\0\2\31\37\0\4\31\1\0\1\31"+
    "\7\0\12\20\2\0\3\31\20\0\11\31\1\0\3\31"+
    "\1\0\26\31\1\0\7\31\1\0\2\31\1\0\5\31"+
    "\3\0\1\31\22\0\1\31\17\0\2\31\4\0\12\20"+
    "\11\0\1\31\13\0\10\31\2\0\2\31\2\0\26\31"+
    "\1\0\7\31\1\0\2\31\1\0\5\31\3\0\1\31"+
    "\36\0\2\31\1\0\3\31\4\0\12\20\1\0\1\31"+
    "\21\0\1\31\1\0\6\31\3\0\3\31\1\0\4\31"+
    "\3\0\2\31\1\0\1\31\1\0\2\31\3\0\2\31"+
    "\3\0\3\31\3\0\14\31\26\0\1\31\25\0\12\20"+
    "\25\0\10\31\1\0\3\31\1\0\27\31\1\0\20\31"+
    "\3\0\1\31\32\0\3\31\5\0\2\31\4\0\12\20"+
    "\20\0\1\31\4\0\10\31\1\0\3\31\1\0\27\31"+
    "\1\0\12\31\1\0\5\31\3\0\1\31\40\0\1\31"+
    "\1\0\2\31\4\0\12\20\1\0\2\31\22\0\10\31"+
    "\1\0\3\31\1\0\51\31\2\0\1\31\20\0\1\31"+
    "\5\0\3\31\10\0\3\31\4\0\12\20\12\0\6\31"+
    "\5\0\22\31\3\0\30\31\1\0\11\31\1\0\1\31"+
    "\2\0\7\31\37\0\12\20\21\0\60\31\1\0\2\31"+
    "\14\0\7\31\11\0\12\20\47\0\2\31\1\0\1\31"+
    "\1\0\5\31\1\0\30\31\1\0\1\31\1\0\12\31"+
    "\1\0\2\31\11\0\1\31\2\0\5\31\1\0\1\31"+
    "\11\0\12\20\2\0\4\31\40\0\1\31\37\0\12\20"+
    "\26\0\10\31\1\0\44\31\33\0\5\31\163\0\53\31"+
    "\24\0\1\31\12\20\6\0\6\31\4\0\4\31\3\0"+
    "\1\31\3\0\2\31\7\0\3\31\4\0\15\31\14\0"+
    "\1\31\1\0\12\20\6\0\46\26\1\0\1\26\5\0"+
    "\1\26\2\0\53\33\1\0\1\31\3\33\u0149\31\1\0"+
    "\4\31\2\0\7\31\1\0\1\31\1\0\4\31\2\0"+
    "\51\31\1\0\4\31\2\0\41\31\1\0\4\31\2\0"+
    "\7\31\1\0\1\31\1\0\4\31\2\0\17\31\1\0"+
    "\71\31\1\0\4\31\2\0\103\31\45\0\20\31\20\0"+
    "\126\26\2\0\6\33\3\0\u016c\31\2\0\21\31\1\0"+
    "\32\31\5\0\113\31\6\0\10\31\7\0\15\31\1\0"+
    "\4\31\16\0\22\31\16\0\22\31\16\0\15\31\1\0"+
    "\3\31\17\0\64\31\43\0\1\31\4\0\1\31\3\0"+
    "\12\20\46\0\12\20\6\0\131\31\7\0\5\31\2\0"+
    "\42\31\1\0\1\31\5\0\106\31\12\0\37\31\47\0"+
    "\12\20\36\31\2\0\5\31\13\0\54\31\4\0\32\31"+
    "\6\0\12\20\46\0\27\31\11\0\65\31\53\0\12\20"+
    "\6\0\12\20\15\0\1\31\135\0\57\31\21\0\7\31"+
    "\4\0\12\20\51\0\36\31\15\0\2\31\12\20\54\31"+
    "\32\0\44\31\34\0\12\20\3\0\3\31\12\20\44\31"+
    "\2\0\11\33\7\0\53\26\2\0\3\26\51\0\4\31"+
    "\1\0\6\31\1\0\2\31\3\0\1\31\5\0\300\33"+
    "\100\0\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\11\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\11\33\10\26\6\33\2\0\6\26\2\0\10\33\10\26"+
    "\10\33\10\26\6\33\2\0\6\26\2\0\10\33\1\0"+
    "\1\26\1\0\1\26\1\0\1\26\1\0\1\26\10\33"+
    "\10\26\16\33\2\0\10\33\10\31\10\33\10\31\10\33"+
    "\10\31\5\33\1\0\2\33\4\26\1\31\1\0\1\33"+
    "\3\0\3\33\1\0\2\33\4\26\1\31\3\0\4\33"+
    "\2\0\2\33\4\26\4\0\10\33\5\26\5\0\3\33"+
    "\1\0\2\33\4\26\1\31\53\0\2\3\107\0\1\33"+
    "\15\0\1\33\20\0\15\33\145\0\1\26\4\0\1\26"+
    "\2\0\1\33\3\26\2\33\3\26\1\33\1\0\1\26"+
    "\3\0\5\26\6\0\1\26\1\0\1\26\1\0\1\26"+
    "\1\0\4\26\1\0\1\33\4\26\1\33\4\31\1\33"+
    "\2\0\2\33\2\26\5\0\1\26\4\33\4\0\1\33"+
    "\21\0\20\54\20\53\3\0\1\26\1\33\u0231\0\32\54"+
    "\32\53\26\0\57\26\1\0\57\33\1\0\1\26\1\33"+
    "\3\26\2\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\4\26\1\33\1\26\2\33\1\26\10\33\3\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\2\33\6\0\1\26\1\33\1\26\1\33\3\0"+
    "\1\26\1\33\14\0\46\33\1\0\1\33\5\0\1\33"+
    "\2\0\70\31\7\0\1\31\20\0\27\31\11\0\7\31"+
    "\1\0\7\31\1\0\7\31\1\0\7\31\1\0\7\31"+
    "\1\0\7\31\1\0\7\31\1\0\7\31\120\0\1\31"+
    "\325\0\2\31\52\0\5\31\5\0\2\31\4\0\126\31"+
    "\6\0\3\31\1\0\132\31\1\0\4\31\5\0\53\31"+
    "\1\0\136\31\21\0\33\31\65\0\306\31\112\0\360\31"+
    "\20\0\215\31\103\0\56\31\2\0\15\31\3\0\20\31"+
    "\12\20\2\31\24\0\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\31\20\0\1\31\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\3\33"+
    "\2\0\106\31\61\0\11\31\2\0\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\3\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\26"+
    "\12\33\1\26\1\33\1\26\1\33\2\26\1\33\1\26"+
    "\1\33\1\26\1\33\1\26\1\33\1\26\1\33\1\31"+
    "\2\0\1\26\1\33\1\26\1\33\1\31\1\26\1\33"+
    "\1\26\3\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\1\26\1\33\5\26\1\33"+
    "\5\26\1\33\1\26\1\33\1\26\1\33\1\26\1\33"+
    "\1\26\1\33\1\26\1\33\2\0\1\26\1\33\3\26"+
    "\60\0\1\31\3\33\7\31\1\0\3\31\1\0\4\31"+
    "\1\0\27\31\35\0\64\31\16\0\62\31\34\0\12\20"+
    "\30\0\6\31\3\0\1\31\1\0\2\31\1\0\12\20"+
    "\34\31\12\0\27\31\31\0\35\31\7\0\57\31\34\0"+
    "\1\31\12\20\6\0\5\31\1\0\12\31\12\20\5\31"+
    "\1\0\51\31\27\0\3\31\1\0\10\31\4\0\12\20"+
    "\6\0\27\31\3\0\1\31\3\0\62\31\1\0\1\31"+
    "\3\0\2\31\2\0\5\31\2\0\1\31\1\0\1\31"+
    "\30\0\3\31\2\0\13\31\7\0\3\31\14\0\6\31"+
    "\2\0\6\31\2\0\6\31\11\0\7\31\1\0\7\31"+
    "\1\0\53\33\1\0\14\33\10\0\120\33\43\31\15\0"+
    "\12\20\6\0\244\31\14\0\27\31\4\0\61\31\4\0"+
    "\u0100\3\156\31\2\0\152\31\46\0\7\33\14\0\5\33"+
    "\5\0\1\31\1\0\12\31\1\0\15\31\1\0\5\31"+
    "\1\0\1\31\1\0\2\31\1\0\2\31\1\0\154\31"+
    "\41\0\153\31\22\0\100\31\2\0\66\31\50\0\14\31"+
    "\164\0\5\31\1\0\207\31\23\0\12\20\7\0\32\26"+
    "\6\0\32\33\13\0\131\31\3\0\6\31\2\0\6\31"+
    "\2\0\6\31\2\0\3\31\43\0\14\31\1\0\32\31"+
    "\1\0\23\31\1\0\2\31\1\0\17\31\2\0\16\31"+
    "\42\0\173\31\205\0\35\31\3\0\61\31\57\0\40\31"+
    "\15\0\24\31\1\0\10\31\6\0\46\31\12\0\36\31"+
    "\2\0\44\31\4\0\10\31\60\0\50\26\50\33\116\31"+
    "\2\0\12\20\6\0\44\26\4\0\44\33\4\0\50\31"+
    "\10\0\64\31\234\0\67\31\11\0\26\31\12\0\10\31"+
    "\230\0\6\31\2\0\1\31\1\0\54\31\1\0\2\31"+
    "\3\0\1\31\2\0\27\31\12\0\27\31\11\0\37\31"+
    "\101\0\23\31\1\0\2\31\12\0\26\31\12\0\32\31"+
    "\106\0\70\31\6\0\2\31\100\0\1\31\17\0\4\31"+
    "\1\0\3\31\1\0\35\31\52\0\35\31\3\0\35\31"+
    "\43\0\10\31\1\0\34\31\33\0\66\31\12\0\26\31"+
    "\12\0\23\31\15\0\22\31\156\0\111\31\67\0\63\26"+
    "\15\0\63\33\15\0\44\31\14\0\12\20\306\0\35\31"+
    "\12\0\1\31\10\0\26\31\232\0\27\31\14\0\65\31"+
    "\56\0\12\20\23\0\55\31\40\0\31\31\7\0\12\20"+
    "\11\0\44\31\17\0\12\20\4\0\1\31\13\0\43\31"+
    "\3\0\1\31\14\0\60\31\16\0\4\31\13\0\12\20"+
    "\1\31\1\0\1\31\43\0\22\31\1\0\31\31\124\0"+
    "\7\31\1\0\1\31\1\0\4\31\1\0\17\31\1\0"+
    "\12\31\7\0\57\31\21\0\12\20\13\0\10\31\2\0"+
    "\2\31\2\0\26\31\1\0\7\31\1\0\2\31\1\0"+
    "\5\31\3\0\1\31\22\0\1\31\14\0\5\31\236\0"+
    "\65\31\22\0\4\31\5\0\12\20\5\0\1\31\40\0"+
    "\60\31\24\0\2\31\1\0\1\31\10\0\12\20\246\0"+
    "\57\31\51\0\4\31\44\0\60\31\24\0\1\31\13\0"+
    "\12\20\46\0\53\31\15\0\1\31\7\0\12\20\66\0"+
    "\33\31\25\0\12\20\306\0\54\31\164\0\40\26\40\33"+
    "\12\20\25\0\1\31\240\0\10\31\2\0\47\31\20\0"+
    "\1\31\1\0\1\31\34\0\1\31\12\0\50\31\7\0"+
    "\1\31\25\0\1\31\13\0\56\31\23\0\1\31\42\0"+
    "\71\31\7\0\11\31\1\0\45\31\21\0\1\31\17\0"+
    "\12\20\30\0\36\31\160\0\7\31\1\0\2\31\1\0"+
    "\46\31\25\0\1\31\11\0\12\20\6\0\6\31\1\0"+
    "\2\31\1\0\40\31\16\0\1\31\7\0\12\20\u0136\0"+
    "\23\31\15\0\232\31\346\0\304\31\274\0\57\31\321\0"+
    "\107\31\271\0\71\31\7\0\37\31\1\0\12\20\146\0"+
    "\36\31\22\0\60\31\20\0\4\31\14\0\12\20\11\0"+
    "\25\31\5\0\23\31\260\0\40\26\40\33\200\0\113\31"+
    "\5\0\1\31\102\0\15\31\100\0\2\31\1\0\1\31"+
    "\34\0\370\31\10\0\363\31\15\0\37\31\61\0\3\31"+
    "\21\0\4\31\10\0\u018c\31\4\0\153\31\5\0\15\31"+
    "\3\0\11\31\7\0\12\31\146\0\32\26\32\33\32\26"+
    "\7\33\1\0\22\33\32\26\32\33\1\26\1\0\2\26"+
    "\2\0\1\26\2\0\2\26\2\0\4\26\1\0\10\26"+
    "\4\33\1\0\1\33\1\0\7\33\1\0\13\33\32\26"+
    "\32\33\2\26\1\0\4\26\2\0\10\26\1\0\7\26"+
    "\1\0\32\33\2\26\1\0\4\26\1\0\5\26\1\0"+
    "\1\26\3\0\7\26\1\0\32\33\32\26\32\33\32\26"+
    "\32\33\32\26\32\33\32\26\32\33\32\26\32\33\32\26"+
    "\34\33\2\0\31\26\1\0\31\33\1\0\6\33\31\26"+
    "\1\0\31\33\1\0\6\33\31\26\1\0\31\33\1\0"+
    "\6\33\31\26\1\0\31\33\1\0\6\33\31\26\1\0"+
    "\31\33\1\0\6\33\1\26\1\33\2\0\62\20\55\31"+
    "\12\0\7\31\2\0\12\20\4\0\1\31\u0171\0\54\31"+
    "\4\0\12\20\6\0\305\31\73\0\42\26\42\33\7\0"+
    "\1\31\4\0\12\20\246\0\4\31\1\0\33\31\1\0"+
    "\2\31\1\0\1\31\2\0\1\31\1\0\12\31\1\0"+
    "\4\31\1\0\1\31\1\0\1\31\6\0\1\31\4\0"+
    "\1\31\1\0\1\31\1\0\1\31\1\0\3\31\1\0"+
    "\2\31\1\0\1\31\2\0\1\31\1\0\1\31\1\0"+
    "\1\31\1\0\1\31\1\0\1\31\1\0\2\31\1\0"+
    "\1\31\2\0\4\31\1\0\7\31\1\0\4\31\1\0"+
    "\4\31\1\0\1\31\1\0\12\31\1\0\21\31\5\0"+
    "\3\31\1\0\5\31\1\0\21\31\164\0\32\54\6\0"+
    "\32\54\6\0\32\54\166\0\327\31\51\0\65\31\13\0"+
    "\336\31\2\0\u0182\31\16\0\u0131\31\37\0\36\31\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28928];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\1\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\11\26"+
    "\1\27\1\2\1\30\1\1\1\2\1\31\1\32\1\33"+
    "\1\34\1\0\1\35\1\36\1\37\1\40\3\26\1\41"+
    "\6\26\1\42\1\43\2\1\4\26\1\44\5\26\1\45"+
    "\1\46\1\26\1\47\1\26\1\50\1\26\1\51\2\26"+
    "\1\52\1\26\1\53\1\26\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\132\0\207\0\264\0\132\0\341"+
    "\0\132\0\132\0\132\0\132\0\132\0\u010e\0\u013b\0\u0168"+
    "\0\u0195\0\132\0\u01c2\0\u01ef\0\u021c\0\u0249\0\132\0\132"+
    "\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\u032a\0\u0357\0\u0384\0\u03b1"+
    "\0\u03de\0\132\0\u040b\0\132\0\u0438\0\u0465\0\132\0\132"+
    "\0\u010e\0\132\0\u0492\0\132\0\132\0\132\0\132\0\u04bf"+
    "\0\u04ec\0\u0519\0\u0276\0\u0546\0\u0573\0\u05a0\0\u05cd\0\u05fa"+
    "\0\u0627\0\132\0\132\0\132\0\u0654\0\u0681\0\u06ae\0\u06db"+
    "\0\u0708\0\u0276\0\u0735\0\u0762\0\u078f\0\u07bc\0\u07e9\0\u0276"+
    "\0\u0816\0\u0843\0\u0276\0\u0870\0\u0276\0\u089d\0\u0276\0\u08ca"+
    "\0\u08f7\0\u0276\0\u0924\0\u0276\0\u0951\0\u0276\0\u0276";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\3\2\31\1\32\1\33\1\34\1\35\1\31\1\36"+
    "\1\37\1\40\1\31\1\41\2\31\1\42\1\43\1\44"+
    "\1\31\1\26\13\45\1\46\3\45\1\3\35\45\57\0"+
    "\1\4\76\0\1\47\40\0\1\50\64\0\1\51\47\0"+
    "\1\52\3\0\1\53\53\0\1\51\1\0\1\20\55\0"+
    "\1\54\57\0\1\55\54\0\1\56\54\0\1\57\50\0"+
    "\1\26\5\0\1\26\2\0\17\26\25\0\1\31\5\0"+
    "\1\31\2\0\17\31\25\0\1\31\5\0\1\31\2\0"+
    "\1\31\1\60\15\31\25\0\1\31\5\0\1\31\2\0"+
    "\7\31\1\61\7\31\25\0\1\31\5\0\1\31\2\0"+
    "\1\31\1\62\15\31\25\0\1\31\5\0\1\31\2\0"+
    "\5\31\1\63\6\31\1\64\2\31\25\0\1\31\5\0"+
    "\1\31\2\0\4\31\1\65\10\31\1\66\1\31\25\0"+
    "\1\31\5\0\1\31\2\0\12\31\1\67\4\31\25\0"+
    "\1\31\5\0\1\31\2\0\4\31\1\70\12\31\25\0"+
    "\1\31\5\0\1\31\2\0\12\31\1\71\4\31\56\0"+
    "\1\72\3\0\13\45\1\0\3\45\1\0\35\45\17\0"+
    "\1\73\35\0\2\53\1\74\2\0\1\75\47\53\20\0"+
    "\1\31\5\0\1\31\2\0\14\31\1\76\2\31\25\0"+
    "\1\31\5\0\1\31\2\0\13\31\1\77\3\31\25\0"+
    "\1\31\5\0\1\31\2\0\7\31\1\100\7\31\25\0"+
    "\1\31\5\0\1\31\2\0\4\31\1\101\12\31\25\0"+
    "\1\31\5\0\1\31\2\0\16\31\1\102\25\0\1\31"+
    "\5\0\1\31\2\0\7\31\1\103\7\31\25\0\1\31"+
    "\5\0\1\31\2\0\6\31\1\104\10\31\25\0\1\31"+
    "\5\0\1\31\2\0\1\31\1\105\12\31\1\106\2\31"+
    "\25\0\1\31\5\0\1\31\2\0\15\31\1\107\1\31"+
    "\7\0\1\74\72\0\1\31\5\0\1\31\2\0\1\31"+
    "\1\110\15\31\25\0\1\31\5\0\1\31\2\0\4\31"+
    "\1\111\12\31\25\0\1\31\5\0\1\31\2\0\13\31"+
    "\1\107\3\31\25\0\1\31\5\0\1\31\2\0\12\31"+
    "\1\112\4\31\25\0\1\31\5\0\1\31\2\0\7\31"+
    "\1\113\7\31\25\0\1\31\5\0\1\31\2\0\10\31"+
    "\1\114\6\31\25\0\1\31\5\0\1\31\2\0\3\31"+
    "\1\115\13\31\25\0\1\31\5\0\1\31\2\0\15\31"+
    "\1\116\1\31\25\0\1\31\5\0\1\31\2\0\4\31"+
    "\1\117\12\31\25\0\1\31\5\0\1\31\2\0\6\31"+
    "\1\120\10\31\25\0\1\31\5\0\1\31\2\0\1\31"+
    "\1\121\15\31\25\0\1\31\5\0\1\31\2\0\14\31"+
    "\1\122\2\31\25\0\1\31\5\0\1\31\2\0\12\31"+
    "\1\123\4\31\25\0\1\31\5\0\1\31\2\0\5\31"+
    "\1\124\11\31\25\0\1\31\5\0\1\31\2\0\14\31"+
    "\1\125\2\31\25\0\1\31\5\0\1\31\2\0\10\31"+
    "\1\126\6\31\25\0\1\31\5\0\1\31\2\0\4\31"+
    "\1\127\12\31\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2430];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\2\11\2\1\1\11\1\1\5\11\4\1"+
    "\1\11\4\1\2\11\11\1\1\11\1\1\1\11\2\1"+
    "\2\11\1\1\1\11\1\0\4\11\12\1\3\11\33\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    
    /* Código arbitrário pode ser inserido diretamente no analisador dessa forma. 
     * Aqui podemos declarar variáveis e métodos adicionais que julgarmos necessários. 
     */
    private int ntk;
    
    public int readedTokens(){
       return ntk;
    }

    private Symbol newToken(short id) {
        return new Symbol(id, yyline+1, yycolumn+1, yylength() ) ;
    }

    private Symbol newToken(short id, Object value) {
        return new Symbol(id, yyline+1, yycolumn+1, yylength() , value) ;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LangLex(java.io.Reader in) {
      ntk = 0; // Isto é copiado direto no construtor do lexer. 
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { return newToken(Terminals.EOF, "end−of−file") ;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 46: break;
          case 2:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
            // fall through
          case 47: break;
          case 3:
            { /* Não faz nada  */
            }
            // fall through
          case 48: break;
          case 4:
            { return new Symbol(Terminals.NOT);
            }
            // fall through
          case 49: break;
          case 5:
            { return new Symbol(Terminals.RES);
            }
            // fall through
          case 50: break;
          case 6:
            { return new Symbol(Terminals.LPAREN);
            }
            // fall through
          case 51: break;
          case 7:
            { return new Symbol(Terminals.RPAREN);
            }
            // fall through
          case 52: break;
          case 8:
            { return new Symbol(Terminals.MULT);
            }
            // fall through
          case 53: break;
          case 9:
            { return new Symbol(Terminals.ADD);
            }
            // fall through
          case 54: break;
          case 10:
            { return new Symbol(Terminals.SUB);
            }
            // fall through
          case 55: break;
          case 11:
            { return new Symbol(Terminals.DOT);
            }
            // fall through
          case 56: break;
          case 12:
            { return new Symbol(Terminals.DIV);
            }
            // fall through
          case 57: break;
          case 13:
            { return new Symbol(Terminals.INT, Integer.parseInt(yytext()) );
            }
            // fall through
          case 58: break;
          case 14:
            { return new Symbol(Terminals.COLON);
            }
            // fall through
          case 59: break;
          case 15:
            { return new Symbol(Terminals.SEMICOLON);
            }
            // fall through
          case 60: break;
          case 16:
            { return new Symbol(Terminals.LESSER);
            }
            // fall through
          case 61: break;
          case 17:
            { return new Symbol(Terminals.EQUAL);
            }
            // fall through
          case 62: break;
          case 18:
            { return new Symbol(Terminals.GREATER);
            }
            // fall through
          case 63: break;
          case 19:
            { return new Symbol(Terminals.TYPE, yytext());
            }
            // fall through
          case 64: break;
          case 20:
            { return new Symbol(Terminals.LBRACK);
            }
            // fall through
          case 65: break;
          case 21:
            { return new Symbol(Terminals.RBRACK);
            }
            // fall through
          case 66: break;
          case 22:
            { return new Symbol(Terminals.ID);
            }
            // fall through
          case 67: break;
          case 23:
            { return new Symbol(Terminals.LBRACE);
            }
            // fall through
          case 68: break;
          case 24:
            { return new Symbol(Terminals.RBRACE);
            }
            // fall through
          case 69: break;
          case 25:
            { return new Symbol(Terminals.DIF);
            }
            // fall through
          case 70: break;
          case 26:
            { return new Symbol(Terminals.AND);
            }
            // fall through
          case 71: break;
          case 27:
            { return new Symbol(Terminals.FLOAT, Float.parseFloat(yytext()) );
            }
            // fall through
          case 72: break;
          case 28:
            { yybegin(COMMENT);
            }
            // fall through
          case 73: break;
          case 29:
            { return new Symbol(Terminals.DOUBLECOLON);
            }
            // fall through
          case 74: break;
          case 30:
            { return new Symbol(Terminals.LESSEREQUAL);
            }
            // fall through
          case 75: break;
          case 31:
            { return new Symbol(Terminals.EQUALTO);
            }
            // fall through
          case 76: break;
          case 32:
            { return new Symbol(Terminals.GREATEREQUAL);
            }
            // fall through
          case 77: break;
          case 33:
            { return new Symbol(Terminals.IF);
            }
            // fall through
          case 78: break;
          case 34:
            { return new Symbol(Terminals.OR);
            }
            // fall through
          case 79: break;
          case 35:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 80: break;
          case 36:
            { return new Symbol(Terminals.NEW);
            }
            // fall through
          case 81: break;
          case 37:
            { return new Symbol(Terminals.DATA);
            }
            // fall through
          case 82: break;
          case 38:
            { return new Symbol(Terminals.ELSE);
            }
            // fall through
          case 83: break;
          case 39:
            { return new Symbol(Terminals.NULL, null);
            }
            // fall through
          case 84: break;
          case 40:
            { return new Symbol(Terminals.READ);
            }
            // fall through
          case 85: break;
          case 41:
            { return new Symbol(Terminals.BOOL, Boolean.parseBoolean(yytext()));
            }
            // fall through
          case 86: break;
          case 42:
            { return new Symbol(Terminals.PRINT);
            }
            // fall through
          case 87: break;
          case 43:
            { return new Symbol(Terminals.ELSEIF);
            }
            // fall through
          case 88: break;
          case 44:
            { return new Symbol(Terminals.RETURN);
            }
            // fall through
          case 89: break;
          case 45:
            { return new Symbol(Terminals.ITERATE);
            }
            // fall through
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
