// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: parsers/Exemplo.jflex


 /*  Esta seção é copiada antes da declaração da classe do analisador léxico.
  *  É nesta seção que se deve incluir imports e declaração de pacotes.
  *  Neste exemplo não temos nada a incluir nesta seção.
  */
  
package src.parsers;

import src.beaver.Symbol;
import src.beaver.Scanner;
import java.math.BigDecimal;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class MiniLangLex extends Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1d00\1\u1e00"+
    "\1\u1f00\1\u2000\2\u2100\1\u2200\7\u2100\1\u2300\1\u2400\1\u2500"+
    "\1\u2100\1\u2600\1\u2700\2\u2100\31\u1100\1\u2800\121\u1100\1\u2900"+
    "\4\u1100\1\u2a00\1\u1100\1\u2b00\1\u2c00\1\u2d00\1\u2e00\1\u2f00"+
    "\1\u3000\53\u1100\1\u3100\10\u3200\31\u2100\1\u1100\1\u3300\1\u3400"+
    "\1\u1100\1\u3500\1\u3600\1\u3700\1\u3800\1\u2100\1\u3900\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u1100\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u2100\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u2100"+
    "\1\u5000\1\u5100\1\u5200\1\u2100\3\u1100\1\u5300\1\u5400\1\u5500"+
    "\12\u2100\4\u1100\1\u5600\17\u2100\2\u1100\1\u5700\41\u2100\2\u1100"+
    "\1\u5800\1\u5900\2\u2100\1\u5a00\1\u5b00\27\u1100\1\u5c00\2\u1100"+
    "\1\u5d00\45\u2100\1\u1100\1\u5e00\1\u5f00\11\u2100\1\u6000\27\u2100"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\11\u2100\1\u6500\1\u6600\5\u2100"+
    "\1\u6700\1\u6800\4\u2100\1\u6900\2\u2100\1\u6a00\16\u2100\246\u1100"+
    "\1\u6b00\20\u1100\1\u6c00\1\u6d00\25\u1100\1\u6e00\34\u1100\1\u6f00"+
    "\14\u2100\2\u1100\1\u7000\u0e05\u2100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\4\0\1\6\2\0\1\7\1\10\1\11\1\12\1\0"+
    "\1\13\1\14\1\15\12\16\1\17\1\20\1\0\1\21"+
    "\1\22\1\23\1\0\32\24\1\25\1\0\1\26\1\0"+
    "\1\27\1\0\32\30\12\0\1\3\44\0\1\30\12\0"+
    "\1\30\4\0\1\30\5\0\27\24\1\0\7\24\30\30"+
    "\1\0\10\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\2\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\2\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\2\24\1\30\1\24\1\30\1\24\3\30\2\24\1\30"+
    "\1\24\1\30\2\24\1\30\3\24\2\30\4\24\1\30"+
    "\2\24\1\30\3\24\3\30\2\24\1\30\2\24\1\30"+
    "\1\24\1\30\1\24\1\30\2\24\1\30\1\24\2\30"+
    "\1\24\1\30\2\24\1\30\3\24\1\30\1\24\1\30"+
    "\2\24\2\30\1\27\1\24\3\30\4\27\1\24\1\27"+
    "\1\30\1\24\1\27\1\30\1\24\1\27\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\2\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\2\30\1\24\1\27\1\30\1\24\1\30\3\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\7\30\2\24\1\30\2\24\2\30\1\24\1\30"+
    "\4\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\105\30\1\27\44\30\7\27\2\30\4\0\14\27"+
    "\16\0\5\30\7\0\1\27\1\0\1\27\126\0\1\31"+
    "\52\0\1\24\1\30\1\24\1\30\1\27\1\0\1\24"+
    "\1\30\2\0\4\30\1\0\1\24\6\0\1\24\1\0"+
    "\3\24\1\0\1\24\1\0\2\24\1\30\21\24\1\0"+
    "\11\24\43\30\1\24\2\30\3\24\3\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\5\30\1\24\1\30"+
    "\1\0\1\24\1\30\2\24\2\30\63\24\60\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\10\0\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\2\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\2\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\0\46\24"+
    "\2\0\1\27\6\0\51\30\107\0\33\27\4\0\4\27"+
    "\55\0\53\27\25\0\12\16\4\0\2\27\1\0\143\27"+
    "\1\0\1\27\17\0\2\27\7\0\2\27\12\16\3\27"+
    "\2\0\1\27\20\0\1\27\1\0\36\27\35\0\131\27"+
    "\13\0\1\27\16\0\12\16\41\27\11\0\2\27\4\0"+
    "\1\27\5\0\26\27\4\0\1\27\11\0\1\27\3\0"+
    "\1\27\27\0\31\27\7\0\13\27\65\0\25\27\1\0"+
    "\10\27\106\0\66\27\3\0\1\27\22\0\1\27\7\0"+
    "\12\27\4\0\12\16\1\0\20\27\4\0\10\27\2\0"+
    "\2\27\2\0\26\27\1\0\7\27\1\0\1\27\3\0"+
    "\4\27\3\0\1\27\20\0\1\27\15\0\2\27\1\0"+
    "\3\27\4\0\12\16\2\27\12\0\1\27\10\0\6\27"+
    "\4\0\2\27\2\0\26\27\1\0\7\27\1\0\2\27"+
    "\1\0\2\27\1\0\2\27\37\0\4\27\1\0\1\27"+
    "\7\0\12\16\2\0\3\27\20\0\11\27\1\0\3\27"+
    "\1\0\26\27\1\0\7\27\1\0\2\27\1\0\5\27"+
    "\3\0\1\27\22\0\1\27\17\0\2\27\4\0\12\16"+
    "\11\0\1\27\13\0\10\27\2\0\2\27\2\0\26\27"+
    "\1\0\7\27\1\0\2\27\1\0\5\27\3\0\1\27"+
    "\36\0\2\27\1\0\3\27\4\0\12\16\1\0\1\27"+
    "\21\0\1\27\1\0\6\27\3\0\3\27\1\0\4\27"+
    "\3\0\2\27\1\0\1\27\1\0\2\27\3\0\2\27"+
    "\3\0\3\27\3\0\14\27\26\0\1\27\25\0\12\16"+
    "\25\0\10\27\1\0\3\27\1\0\27\27\1\0\20\27"+
    "\3\0\1\27\32\0\3\27\5\0\2\27\4\0\12\16"+
    "\20\0\1\27\4\0\10\27\1\0\3\27\1\0\27\27"+
    "\1\0\12\27\1\0\5\27\3\0\1\27\40\0\1\27"+
    "\1\0\2\27\4\0\12\16\1\0\2\27\22\0\10\27"+
    "\1\0\3\27\1\0\51\27\2\0\1\27\20\0\1\27"+
    "\5\0\3\27\10\0\3\27\4\0\12\16\12\0\6\27"+
    "\5\0\22\27\3\0\30\27\1\0\11\27\1\0\1\27"+
    "\2\0\7\27\37\0\12\16\21\0\60\27\1\0\2\27"+
    "\14\0\7\27\11\0\12\16\47\0\2\27\1\0\1\27"+
    "\1\0\5\27\1\0\30\27\1\0\1\27\1\0\12\27"+
    "\1\0\2\27\11\0\1\27\2\0\5\27\1\0\1\27"+
    "\11\0\12\16\2\0\4\27\40\0\1\27\37\0\12\16"+
    "\26\0\10\27\1\0\44\27\33\0\5\27\163\0\53\27"+
    "\24\0\1\27\12\16\6\0\6\27\4\0\4\27\3\0"+
    "\1\27\3\0\2\27\7\0\3\27\4\0\15\27\14\0"+
    "\1\27\1\0\12\16\6\0\46\24\1\0\1\24\5\0"+
    "\1\24\2\0\53\30\1\0\1\27\3\30\u0149\27\1\0"+
    "\4\27\2\0\7\27\1\0\1\27\1\0\4\27\2\0"+
    "\51\27\1\0\4\27\2\0\41\27\1\0\4\27\2\0"+
    "\7\27\1\0\1\27\1\0\4\27\2\0\17\27\1\0"+
    "\71\27\1\0\4\27\2\0\103\27\45\0\20\27\20\0"+
    "\126\24\2\0\6\30\3\0\u016c\27\2\0\21\27\1\0"+
    "\32\27\5\0\113\27\6\0\10\27\7\0\15\27\1\0"+
    "\4\27\16\0\22\27\16\0\22\27\16\0\15\27\1\0"+
    "\3\27\17\0\64\27\43\0\1\27\4\0\1\27\3\0"+
    "\12\16\46\0\12\16\6\0\131\27\7\0\5\27\2\0"+
    "\42\27\1\0\1\27\5\0\106\27\12\0\37\27\47\0"+
    "\12\16\36\27\2\0\5\27\13\0\54\27\4\0\32\27"+
    "\6\0\12\16\46\0\27\27\11\0\65\27\53\0\12\16"+
    "\6\0\12\16\15\0\1\27\135\0\57\27\21\0\7\27"+
    "\4\0\12\16\51\0\36\27\15\0\2\27\12\16\54\27"+
    "\32\0\44\27\34\0\12\16\3\0\3\27\12\16\44\27"+
    "\2\0\11\30\7\0\53\24\2\0\3\24\51\0\4\27"+
    "\1\0\6\27\1\0\2\27\3\0\1\27\5\0\300\30"+
    "\100\0\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\11\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\11\30\10\24\6\30\2\0\6\24\2\0\10\30\10\24"+
    "\10\30\10\24\6\30\2\0\6\24\2\0\10\30\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\10\30"+
    "\10\24\16\30\2\0\10\30\10\27\10\30\10\27\10\30"+
    "\10\27\5\30\1\0\2\30\4\24\1\27\1\0\1\30"+
    "\3\0\3\30\1\0\2\30\4\24\1\27\3\0\4\30"+
    "\2\0\2\30\4\24\4\0\10\30\5\24\5\0\3\30"+
    "\1\0\2\30\4\24\1\27\53\0\2\3\107\0\1\30"+
    "\15\0\1\30\20\0\15\30\145\0\1\24\4\0\1\24"+
    "\2\0\1\30\3\24\2\30\3\24\1\30\1\0\1\24"+
    "\3\0\5\24\6\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\4\24\1\0\1\30\4\24\1\30\4\27\1\30"+
    "\2\0\2\30\2\24\5\0\1\24\4\30\4\0\1\30"+
    "\21\0\20\32\20\31\3\0\1\24\1\30\u0231\0\32\32"+
    "\32\31\26\0\57\24\1\0\57\30\1\0\1\24\1\30"+
    "\3\24\2\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\4\24\1\30\1\24\2\30\1\24\10\30\3\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\2\30\6\0\1\24\1\30\1\24\1\30\3\0"+
    "\1\24\1\30\14\0\46\30\1\0\1\30\5\0\1\30"+
    "\2\0\70\27\7\0\1\27\20\0\27\27\11\0\7\27"+
    "\1\0\7\27\1\0\7\27\1\0\7\27\1\0\7\27"+
    "\1\0\7\27\1\0\7\27\1\0\7\27\120\0\1\27"+
    "\325\0\2\27\52\0\5\27\5\0\2\27\4\0\126\27"+
    "\6\0\3\27\1\0\132\27\1\0\4\27\5\0\53\27"+
    "\1\0\136\27\21\0\33\27\65\0\306\27\112\0\360\27"+
    "\20\0\215\27\103\0\56\27\2\0\15\27\3\0\20\27"+
    "\12\16\2\27\24\0\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\27\20\0\1\27\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\3\30"+
    "\2\0\106\27\61\0\11\27\2\0\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\3\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\24"+
    "\12\30\1\24\1\30\1\24\1\30\2\24\1\30\1\24"+
    "\1\30\1\24\1\30\1\24\1\30\1\24\1\30\1\27"+
    "\2\0\1\24\1\30\1\24\1\30\1\27\1\24\1\30"+
    "\1\24\3\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\1\24\1\30\5\24\1\30"+
    "\5\24\1\30\1\24\1\30\1\24\1\30\1\24\1\30"+
    "\1\24\1\30\1\24\1\30\2\0\1\24\1\30\3\24"+
    "\60\0\1\27\3\30\7\27\1\0\3\27\1\0\4\27"+
    "\1\0\27\27\35\0\64\27\16\0\62\27\34\0\12\16"+
    "\30\0\6\27\3\0\1\27\1\0\2\27\1\0\12\16"+
    "\34\27\12\0\27\27\31\0\35\27\7\0\57\27\34\0"+
    "\1\27\12\16\6\0\5\27\1\0\12\27\12\16\5\27"+
    "\1\0\51\27\27\0\3\27\1\0\10\27\4\0\12\16"+
    "\6\0\27\27\3\0\1\27\3\0\62\27\1\0\1\27"+
    "\3\0\2\27\2\0\5\27\2\0\1\27\1\0\1\27"+
    "\30\0\3\27\2\0\13\27\7\0\3\27\14\0\6\27"+
    "\2\0\6\27\2\0\6\27\11\0\7\27\1\0\7\27"+
    "\1\0\53\30\1\0\14\30\10\0\120\30\43\27\15\0"+
    "\12\16\6\0\244\27\14\0\27\27\4\0\61\27\4\0"+
    "\u0100\3\156\27\2\0\152\27\46\0\7\30\14\0\5\30"+
    "\5\0\1\27\1\0\12\27\1\0\15\27\1\0\5\27"+
    "\1\0\1\27\1\0\2\27\1\0\2\27\1\0\154\27"+
    "\41\0\153\27\22\0\100\27\2\0\66\27\50\0\14\27"+
    "\164\0\5\27\1\0\207\27\23\0\12\16\7\0\32\24"+
    "\6\0\32\30\13\0\131\27\3\0\6\27\2\0\6\27"+
    "\2\0\6\27\2\0\3\27\43\0\14\27\1\0\32\27"+
    "\1\0\23\27\1\0\2\27\1\0\17\27\2\0\16\27"+
    "\42\0\173\27\205\0\35\27\3\0\61\27\57\0\40\27"+
    "\15\0\24\27\1\0\10\27\6\0\46\27\12\0\36\27"+
    "\2\0\44\27\4\0\10\27\60\0\50\24\50\30\116\27"+
    "\2\0\12\16\6\0\44\24\4\0\44\30\4\0\50\27"+
    "\10\0\64\27\234\0\67\27\11\0\26\27\12\0\10\27"+
    "\230\0\6\27\2\0\1\27\1\0\54\27\1\0\2\27"+
    "\3\0\1\27\2\0\27\27\12\0\27\27\11\0\37\27"+
    "\101\0\23\27\1\0\2\27\12\0\26\27\12\0\32\27"+
    "\106\0\70\27\6\0\2\27\100\0\1\27\17\0\4\27"+
    "\1\0\3\27\1\0\35\27\52\0\35\27\3\0\35\27"+
    "\43\0\10\27\1\0\34\27\33\0\66\27\12\0\26\27"+
    "\12\0\23\27\15\0\22\27\156\0\111\27\67\0\63\24"+
    "\15\0\63\30\15\0\44\27\14\0\12\16\306\0\35\27"+
    "\12\0\1\27\10\0\26\27\232\0\27\27\14\0\65\27"+
    "\56\0\12\16\23\0\55\27\40\0\31\27\7\0\12\16"+
    "\11\0\44\27\17\0\12\16\4\0\1\27\13\0\43\27"+
    "\3\0\1\27\14\0\60\27\16\0\4\27\13\0\12\16"+
    "\1\27\1\0\1\27\43\0\22\27\1\0\31\27\124\0"+
    "\7\27\1\0\1\27\1\0\4\27\1\0\17\27\1\0"+
    "\12\27\7\0\57\27\21\0\12\16\13\0\10\27\2\0"+
    "\2\27\2\0\26\27\1\0\7\27\1\0\2\27\1\0"+
    "\5\27\3\0\1\27\22\0\1\27\14\0\5\27\236\0"+
    "\65\27\22\0\4\27\5\0\12\16\5\0\1\27\40\0"+
    "\60\27\24\0\2\27\1\0\1\27\10\0\12\16\246\0"+
    "\57\27\51\0\4\27\44\0\60\27\24\0\1\27\13\0"+
    "\12\16\46\0\53\27\15\0\1\27\7\0\12\16\66\0"+
    "\33\27\25\0\12\16\306\0\54\27\164\0\40\24\40\30"+
    "\12\16\25\0\1\27\240\0\10\27\2\0\47\27\20\0"+
    "\1\27\1\0\1\27\34\0\1\27\12\0\50\27\7\0"+
    "\1\27\25\0\1\27\13\0\56\27\23\0\1\27\42\0"+
    "\71\27\7\0\11\27\1\0\45\27\21\0\1\27\17\0"+
    "\12\16\30\0\36\27\160\0\7\27\1\0\2\27\1\0"+
    "\46\27\25\0\1\27\11\0\12\16\6\0\6\27\1\0"+
    "\2\27\1\0\40\27\16\0\1\27\7\0\12\16\u0136\0"+
    "\23\27\15\0\232\27\346\0\304\27\274\0\57\27\321\0"+
    "\107\27\271\0\71\27\7\0\37\27\1\0\12\16\146\0"+
    "\36\27\22\0\60\27\20\0\4\27\14\0\12\16\11\0"+
    "\25\27\5\0\23\27\260\0\40\24\40\30\200\0\113\27"+
    "\5\0\1\27\102\0\15\27\100\0\2\27\1\0\1\27"+
    "\34\0\370\27\10\0\363\27\15\0\37\27\61\0\3\27"+
    "\21\0\4\27\10\0\u018c\27\4\0\153\27\5\0\15\27"+
    "\3\0\11\27\7\0\12\27\146\0\32\24\32\30\32\24"+
    "\7\30\1\0\22\30\32\24\32\30\1\24\1\0\2\24"+
    "\2\0\1\24\2\0\2\24\2\0\4\24\1\0\10\24"+
    "\4\30\1\0\1\30\1\0\7\30\1\0\13\30\32\24"+
    "\32\30\2\24\1\0\4\24\2\0\10\24\1\0\7\24"+
    "\1\0\32\30\2\24\1\0\4\24\1\0\5\24\1\0"+
    "\1\24\3\0\7\24\1\0\32\30\32\24\32\30\32\24"+
    "\32\30\32\24\32\30\32\24\32\30\32\24\32\30\32\24"+
    "\34\30\2\0\31\24\1\0\31\30\1\0\6\30\31\24"+
    "\1\0\31\30\1\0\6\30\31\24\1\0\31\30\1\0"+
    "\6\30\31\24\1\0\31\30\1\0\6\30\31\24\1\0"+
    "\31\30\1\0\6\30\1\24\1\30\2\0\62\16\55\27"+
    "\12\0\7\27\2\0\12\16\4\0\1\27\u0171\0\54\27"+
    "\4\0\12\16\6\0\305\27\73\0\42\24\42\30\7\0"+
    "\1\27\4\0\12\16\246\0\4\27\1\0\33\27\1\0"+
    "\2\27\1\0\1\27\2\0\1\27\1\0\12\27\1\0"+
    "\4\27\1\0\1\27\1\0\1\27\6\0\1\27\4\0"+
    "\1\27\1\0\1\27\1\0\1\27\1\0\3\27\1\0"+
    "\2\27\1\0\1\27\2\0\1\27\1\0\1\27\1\0"+
    "\1\27\1\0\1\27\1\0\1\27\1\0\2\27\1\0"+
    "\1\27\2\0\4\27\1\0\7\27\1\0\4\27\1\0"+
    "\4\27\1\0\1\27\1\0\12\27\1\0\21\27\5\0"+
    "\3\27\1\0\5\27\1\0\21\27\164\0\32\32\6\0"+
    "\32\32\6\0\32\32\166\0\327\27\51\0\65\27\13\0"+
    "\336\27\2\0\u0182\27\16\0\u0131\27\37\0\36\27\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28928];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\4\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\1\1\2"+
    "\1\25\1\0\1\26\2\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[30];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\33\0\66\0\66\0\121\0\66\0\66\0\66"+
    "\0\66\0\66\0\66\0\154\0\207\0\242\0\66\0\66"+
    "\0\66\0\66\0\66\0\275\0\66\0\66\0\330\0\363"+
    "\0\u010e\0\66\0\u0129\0\66\0\66\0\u0144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[30];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\3\2\27"+
    "\1\24\11\30\1\31\3\30\1\3\15\30\35\0\1\4"+
    "\46\0\1\14\25\0\1\32\3\0\1\33\31\0\1\14"+
    "\1\0\1\16\32\0\1\24\5\0\1\24\2\0\2\24"+
    "\20\0\1\27\5\0\1\27\2\0\2\27\2\0\11\30"+
    "\1\0\3\30\1\0\15\30\15\0\1\34\15\0\2\33"+
    "\1\35\2\0\1\36\25\33\2\0\1\35\30\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[351];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\2\11\1\1\6\11\3\1\5\11\1\1"+
    "\2\11\3\1\1\11\1\0\2\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[30];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	private Symbol newToken(short id)
	{
		return new Symbol(id, yyline + 1, yycolumn + 1, yylength());
	}

	private Symbol newToken(short id, Object value)
	{
		return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MiniLangLex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	return newToken(Terminals.EOF, "end-of-file");
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 23: break;
          case 2:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
            // fall through
          case 24: break;
          case 3:
            { /* Não faz nada  */
            }
            // fall through
          case 25: break;
          case 4:
            { return newToken(Terminals.DIV);
            }
            // fall through
          case 26: break;
          case 5:
            { return newToken(Terminals.AP);
            }
            // fall through
          case 27: break;
          case 6:
            { return newToken(Terminals.FP);
            }
            // fall through
          case 28: break;
          case 7:
            { return newToken(Terminals.MULT);
            }
            // fall through
          case 29: break;
          case 8:
            { return newToken(Terminals.PLUS);
            }
            // fall through
          case 30: break;
          case 9:
            { return newToken(Terminals.SUB);
            }
            // fall through
          case 31: break;
          case 10:
            { return newToken(Terminals.FLOAT, Float.parseFloat(yytext()) );
            }
            // fall through
          case 32: break;
          case 11:
            { return newToken(Terminals.INT, Integer.parseInt(yytext()) );
            }
            // fall through
          case 33: break;
          case 12:
            { return newToken(Terminals.COLON);
            }
            // fall through
          case 34: break;
          case 13:
            { return newToken(Terminals.SEMI);
            }
            // fall through
          case 35: break;
          case 14:
            { return newToken(Terminals.EQ);
            }
            // fall through
          case 36: break;
          case 15:
            { return newToken(Terminals.GREATER);
            }
            // fall through
          case 37: break;
          case 16:
            { return newToken(Terminals.IF);
            }
            // fall through
          case 38: break;
          case 17:
            { return newToken(Terminals.TYPE, yytext());
            }
            // fall through
          case 39: break;
          case 18:
            { return newToken(Terminals.LB);
            }
            // fall through
          case 40: break;
          case 19:
            { return newToken(Terminals.RB);
            }
            // fall through
          case 41: break;
          case 20:
            { return newToken(Terminals.ID, yytext());
            }
            // fall through
          case 42: break;
          case 21:
            { yybegin(COMMENT);
            }
            // fall through
          case 43: break;
          case 22:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 44: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
