// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: parsers/lang.jflex


//Nathan Toschi Reis / 201865064C
//Felippe Rocha Lobo de Abreu / 201765185AC

 /*  Esta seção é copiada antes da declaração da classe do analisador léxico.
  *  É nesta seção que se deve incluir imports e declaração de pacotes.
  *  Neste exemplo não temos nada a incluir nesta seção.
  */
  
package src.parsers;

import src.beaver.Symbol;
import src.beaver.Scanner;
import java.math.BigDecimal;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class MiniLangLex extends Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1d00\1\u1e00"+
    "\1\u1f00\1\u2000\2\u2100\1\u2200\7\u2100\1\u2300\1\u2400\1\u2500"+
    "\1\u2100\1\u2600\1\u2700\2\u2100\31\u1100\1\u2800\121\u1100\1\u2900"+
    "\4\u1100\1\u2a00\1\u1100\1\u2b00\1\u2c00\1\u2d00\1\u2e00\1\u2f00"+
    "\1\u3000\53\u1100\1\u3100\10\u3200\31\u2100\1\u1100\1\u3300\1\u3400"+
    "\1\u1100\1\u3500\1\u3600\1\u3700\1\u3800\1\u2100\1\u3900\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u1100\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u2100\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800"+
    "\1\u4900\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u2100"+
    "\1\u5000\1\u5100\1\u5200\1\u2100\3\u1100\1\u5300\1\u5400\1\u5500"+
    "\12\u2100\4\u1100\1\u5600\17\u2100\2\u1100\1\u5700\41\u2100\2\u1100"+
    "\1\u5800\1\u5900\2\u2100\1\u5a00\1\u5b00\27\u1100\1\u5c00\2\u1100"+
    "\1\u5d00\45\u2100\1\u1100\1\u5e00\1\u5f00\11\u2100\1\u6000\27\u2100"+
    "\1\u6100\1\u6200\1\u6300\1\u6400\11\u2100\1\u6500\1\u6600\5\u2100"+
    "\1\u6700\1\u6800\4\u2100\1\u6900\2\u2100\1\u6a00\16\u2100\246\u1100"+
    "\1\u6b00\20\u1100\1\u6c00\1\u6d00\25\u1100\1\u6e00\34\u1100\1\u6f00"+
    "\14\u2100\2\u1100\1\u7000\u0e05\u2100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\3\0\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\12\22\1\23\1\24"+
    "\1\25\1\26\1\27\2\0\32\30\1\31\1\0\1\32"+
    "\1\0\1\33\1\0\1\34\2\35\1\36\1\37\1\40"+
    "\2\35\1\41\2\35\1\42\1\35\1\43\1\35\1\44"+
    "\1\35\1\45\1\46\1\47\1\50\1\35\1\51\3\35"+
    "\1\52\1\0\1\53\7\0\1\3\44\0\1\35\12\0"+
    "\1\35\4\0\1\35\5\0\27\30\1\0\7\30\30\35"+
    "\1\0\10\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\2\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\2\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\2\30\1\35\1\30\1\35\1\30\3\35\2\30\1\35"+
    "\1\30\1\35\2\30\1\35\3\30\2\35\4\30\1\35"+
    "\2\30\1\35\3\30\3\35\2\30\1\35\2\30\1\35"+
    "\1\30\1\35\1\30\1\35\2\30\1\35\1\30\2\35"+
    "\1\30\1\35\2\30\1\35\3\30\1\35\1\30\1\35"+
    "\2\30\2\35\1\54\1\30\3\35\4\54\1\30\1\54"+
    "\1\35\1\30\1\54\1\35\1\30\1\54\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\2\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\2\35\1\30\1\54\1\35\1\30\1\35\3\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\7\35\2\30\1\35\2\30\2\35\1\30\1\35"+
    "\4\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\105\35\1\54\44\35\7\54\2\35\4\0\14\54"+
    "\16\0\5\35\7\0\1\54\1\0\1\54\126\0\1\55"+
    "\52\0\1\30\1\35\1\30\1\35\1\54\1\0\1\30"+
    "\1\35\2\0\4\35\1\0\1\30\6\0\1\30\1\0"+
    "\3\30\1\0\1\30\1\0\2\30\1\35\21\30\1\0"+
    "\11\30\43\35\1\30\2\35\3\30\3\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\5\35\1\30\1\35"+
    "\1\0\1\30\1\35\2\30\2\35\63\30\60\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\10\0\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\2\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\2\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\0\46\30"+
    "\2\0\1\54\6\0\51\35\107\0\33\54\4\0\4\54"+
    "\55\0\53\54\25\0\12\22\4\0\2\54\1\0\143\54"+
    "\1\0\1\54\17\0\2\54\7\0\2\54\12\22\3\54"+
    "\2\0\1\54\20\0\1\54\1\0\36\54\35\0\131\54"+
    "\13\0\1\54\16\0\12\22\41\54\11\0\2\54\4\0"+
    "\1\54\5\0\26\54\4\0\1\54\11\0\1\54\3\0"+
    "\1\54\27\0\31\54\7\0\13\54\65\0\25\54\1\0"+
    "\10\54\106\0\66\54\3\0\1\54\22\0\1\54\7\0"+
    "\12\54\4\0\12\22\1\0\20\54\4\0\10\54\2\0"+
    "\2\54\2\0\26\54\1\0\7\54\1\0\1\54\3\0"+
    "\4\54\3\0\1\54\20\0\1\54\15\0\2\54\1\0"+
    "\3\54\4\0\12\22\2\54\12\0\1\54\10\0\6\54"+
    "\4\0\2\54\2\0\26\54\1\0\7\54\1\0\2\54"+
    "\1\0\2\54\1\0\2\54\37\0\4\54\1\0\1\54"+
    "\7\0\12\22\2\0\3\54\20\0\11\54\1\0\3\54"+
    "\1\0\26\54\1\0\7\54\1\0\2\54\1\0\5\54"+
    "\3\0\1\54\22\0\1\54\17\0\2\54\4\0\12\22"+
    "\11\0\1\54\13\0\10\54\2\0\2\54\2\0\26\54"+
    "\1\0\7\54\1\0\2\54\1\0\5\54\3\0\1\54"+
    "\36\0\2\54\1\0\3\54\4\0\12\22\1\0\1\54"+
    "\21\0\1\54\1\0\6\54\3\0\3\54\1\0\4\54"+
    "\3\0\2\54\1\0\1\54\1\0\2\54\3\0\2\54"+
    "\3\0\3\54\3\0\14\54\26\0\1\54\25\0\12\22"+
    "\25\0\10\54\1\0\3\54\1\0\27\54\1\0\20\54"+
    "\3\0\1\54\32\0\3\54\5\0\2\54\4\0\12\22"+
    "\20\0\1\54\4\0\10\54\1\0\3\54\1\0\27\54"+
    "\1\0\12\54\1\0\5\54\3\0\1\54\40\0\1\54"+
    "\1\0\2\54\4\0\12\22\1\0\2\54\22\0\10\54"+
    "\1\0\3\54\1\0\51\54\2\0\1\54\20\0\1\54"+
    "\5\0\3\54\10\0\3\54\4\0\12\22\12\0\6\54"+
    "\5\0\22\54\3\0\30\54\1\0\11\54\1\0\1\54"+
    "\2\0\7\54\37\0\12\22\21\0\60\54\1\0\2\54"+
    "\14\0\7\54\11\0\12\22\47\0\2\54\1\0\1\54"+
    "\1\0\5\54\1\0\30\54\1\0\1\54\1\0\12\54"+
    "\1\0\2\54\11\0\1\54\2\0\5\54\1\0\1\54"+
    "\11\0\12\22\2\0\4\54\40\0\1\54\37\0\12\22"+
    "\26\0\10\54\1\0\44\54\33\0\5\54\163\0\53\54"+
    "\24\0\1\54\12\22\6\0\6\54\4\0\4\54\3\0"+
    "\1\54\3\0\2\54\7\0\3\54\4\0\15\54\14\0"+
    "\1\54\1\0\12\22\6\0\46\30\1\0\1\30\5\0"+
    "\1\30\2\0\53\35\1\0\1\54\3\35\u0149\54\1\0"+
    "\4\54\2\0\7\54\1\0\1\54\1\0\4\54\2\0"+
    "\51\54\1\0\4\54\2\0\41\54\1\0\4\54\2\0"+
    "\7\54\1\0\1\54\1\0\4\54\2\0\17\54\1\0"+
    "\71\54\1\0\4\54\2\0\103\54\45\0\20\54\20\0"+
    "\126\30\2\0\6\35\3\0\u016c\54\2\0\21\54\1\0"+
    "\32\54\5\0\113\54\6\0\10\54\7\0\15\54\1\0"+
    "\4\54\16\0\22\54\16\0\22\54\16\0\15\54\1\0"+
    "\3\54\17\0\64\54\43\0\1\54\4\0\1\54\3\0"+
    "\12\22\46\0\12\22\6\0\131\54\7\0\5\54\2\0"+
    "\42\54\1\0\1\54\5\0\106\54\12\0\37\54\47\0"+
    "\12\22\36\54\2\0\5\54\13\0\54\54\4\0\32\54"+
    "\6\0\12\22\46\0\27\54\11\0\65\54\53\0\12\22"+
    "\6\0\12\22\15\0\1\54\135\0\57\54\21\0\7\54"+
    "\4\0\12\22\51\0\36\54\15\0\2\54\12\22\54\54"+
    "\32\0\44\54\34\0\12\22\3\0\3\54\12\22\44\54"+
    "\2\0\11\35\7\0\53\30\2\0\3\30\51\0\4\54"+
    "\1\0\6\54\1\0\2\54\3\0\1\54\5\0\300\35"+
    "\100\0\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\11\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\11\35\10\30\6\35\2\0\6\30\2\0\10\35\10\30"+
    "\10\35\10\30\6\35\2\0\6\30\2\0\10\35\1\0"+
    "\1\30\1\0\1\30\1\0\1\30\1\0\1\30\10\35"+
    "\10\30\16\35\2\0\10\35\10\54\10\35\10\54\10\35"+
    "\10\54\5\35\1\0\2\35\4\30\1\54\1\0\1\35"+
    "\3\0\3\35\1\0\2\35\4\30\1\54\3\0\4\35"+
    "\2\0\2\35\4\30\4\0\10\35\5\30\5\0\3\35"+
    "\1\0\2\35\4\30\1\54\53\0\2\3\107\0\1\35"+
    "\15\0\1\35\20\0\15\35\145\0\1\30\4\0\1\30"+
    "\2\0\1\35\3\30\2\35\3\30\1\35\1\0\1\30"+
    "\3\0\5\30\6\0\1\30\1\0\1\30\1\0\1\30"+
    "\1\0\4\30\1\0\1\35\4\30\1\35\4\54\1\35"+
    "\2\0\2\35\2\30\5\0\1\30\4\35\4\0\1\35"+
    "\21\0\20\56\20\55\3\0\1\30\1\35\u0231\0\32\56"+
    "\32\55\26\0\57\30\1\0\57\35\1\0\1\30\1\35"+
    "\3\30\2\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\4\30\1\35\1\30\2\35\1\30\10\35\3\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\2\35\6\0\1\30\1\35\1\30\1\35\3\0"+
    "\1\30\1\35\14\0\46\35\1\0\1\35\5\0\1\35"+
    "\2\0\70\54\7\0\1\54\20\0\27\54\11\0\7\54"+
    "\1\0\7\54\1\0\7\54\1\0\7\54\1\0\7\54"+
    "\1\0\7\54\1\0\7\54\1\0\7\54\120\0\1\54"+
    "\325\0\2\54\52\0\5\54\5\0\2\54\4\0\126\54"+
    "\6\0\3\54\1\0\132\54\1\0\4\54\5\0\53\54"+
    "\1\0\136\54\21\0\33\54\65\0\306\54\112\0\360\54"+
    "\20\0\215\54\103\0\56\54\2\0\15\54\3\0\20\54"+
    "\12\22\2\54\24\0\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\54\20\0\1\54\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\3\35"+
    "\2\0\106\54\61\0\11\54\2\0\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\3\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\30"+
    "\12\35\1\30\1\35\1\30\1\35\2\30\1\35\1\30"+
    "\1\35\1\30\1\35\1\30\1\35\1\30\1\35\1\54"+
    "\2\0\1\30\1\35\1\30\1\35\1\54\1\30\1\35"+
    "\1\30\3\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\1\30\1\35\5\30\1\35"+
    "\5\30\1\35\1\30\1\35\1\30\1\35\1\30\1\35"+
    "\1\30\1\35\1\30\1\35\2\0\1\30\1\35\3\30"+
    "\60\0\1\54\3\35\7\54\1\0\3\54\1\0\4\54"+
    "\1\0\27\54\35\0\64\54\16\0\62\54\34\0\12\22"+
    "\30\0\6\54\3\0\1\54\1\0\2\54\1\0\12\22"+
    "\34\54\12\0\27\54\31\0\35\54\7\0\57\54\34\0"+
    "\1\54\12\22\6\0\5\54\1\0\12\54\12\22\5\54"+
    "\1\0\51\54\27\0\3\54\1\0\10\54\4\0\12\22"+
    "\6\0\27\54\3\0\1\54\3\0\62\54\1\0\1\54"+
    "\3\0\2\54\2\0\5\54\2\0\1\54\1\0\1\54"+
    "\30\0\3\54\2\0\13\54\7\0\3\54\14\0\6\54"+
    "\2\0\6\54\2\0\6\54\11\0\7\54\1\0\7\54"+
    "\1\0\53\35\1\0\14\35\10\0\120\35\43\54\15\0"+
    "\12\22\6\0\244\54\14\0\27\54\4\0\61\54\4\0"+
    "\u0100\3\156\54\2\0\152\54\46\0\7\35\14\0\5\35"+
    "\5\0\1\54\1\0\12\54\1\0\15\54\1\0\5\54"+
    "\1\0\1\54\1\0\2\54\1\0\2\54\1\0\154\54"+
    "\41\0\153\54\22\0\100\54\2\0\66\54\50\0\14\54"+
    "\164\0\5\54\1\0\207\54\23\0\12\22\7\0\32\30"+
    "\6\0\32\35\13\0\131\54\3\0\6\54\2\0\6\54"+
    "\2\0\6\54\2\0\3\54\43\0\14\54\1\0\32\54"+
    "\1\0\23\54\1\0\2\54\1\0\17\54\2\0\16\54"+
    "\42\0\173\54\205\0\35\54\3\0\61\54\57\0\40\54"+
    "\15\0\24\54\1\0\10\54\6\0\46\54\12\0\36\54"+
    "\2\0\44\54\4\0\10\54\60\0\50\30\50\35\116\54"+
    "\2\0\12\22\6\0\44\30\4\0\44\35\4\0\50\54"+
    "\10\0\64\54\234\0\67\54\11\0\26\54\12\0\10\54"+
    "\230\0\6\54\2\0\1\54\1\0\54\54\1\0\2\54"+
    "\3\0\1\54\2\0\27\54\12\0\27\54\11\0\37\54"+
    "\101\0\23\54\1\0\2\54\12\0\26\54\12\0\32\54"+
    "\106\0\70\54\6\0\2\54\100\0\1\54\17\0\4\54"+
    "\1\0\3\54\1\0\35\54\52\0\35\54\3\0\35\54"+
    "\43\0\10\54\1\0\34\54\33\0\66\54\12\0\26\54"+
    "\12\0\23\54\15\0\22\54\156\0\111\54\67\0\63\30"+
    "\15\0\63\35\15\0\44\54\14\0\12\22\306\0\35\54"+
    "\12\0\1\54\10\0\26\54\232\0\27\54\14\0\65\54"+
    "\56\0\12\22\23\0\55\54\40\0\31\54\7\0\12\22"+
    "\11\0\44\54\17\0\12\22\4\0\1\54\13\0\43\54"+
    "\3\0\1\54\14\0\60\54\16\0\4\54\13\0\12\22"+
    "\1\54\1\0\1\54\43\0\22\54\1\0\31\54\124\0"+
    "\7\54\1\0\1\54\1\0\4\54\1\0\17\54\1\0"+
    "\12\54\7\0\57\54\21\0\12\22\13\0\10\54\2\0"+
    "\2\54\2\0\26\54\1\0\7\54\1\0\2\54\1\0"+
    "\5\54\3\0\1\54\22\0\1\54\14\0\5\54\236\0"+
    "\65\54\22\0\4\54\5\0\12\22\5\0\1\54\40\0"+
    "\60\54\24\0\2\54\1\0\1\54\10\0\12\22\246\0"+
    "\57\54\51\0\4\54\44\0\60\54\24\0\1\54\13\0"+
    "\12\22\46\0\53\54\15\0\1\54\7\0\12\22\66\0"+
    "\33\54\25\0\12\22\306\0\54\54\164\0\40\30\40\35"+
    "\12\22\25\0\1\54\240\0\10\54\2\0\47\54\20\0"+
    "\1\54\1\0\1\54\34\0\1\54\12\0\50\54\7\0"+
    "\1\54\25\0\1\54\13\0\56\54\23\0\1\54\42\0"+
    "\71\54\7\0\11\54\1\0\45\54\21\0\1\54\17\0"+
    "\12\22\30\0\36\54\160\0\7\54\1\0\2\54\1\0"+
    "\46\54\25\0\1\54\11\0\12\22\6\0\6\54\1\0"+
    "\2\54\1\0\40\54\16\0\1\54\7\0\12\22\u0136\0"+
    "\23\54\15\0\232\54\346\0\304\54\274\0\57\54\321\0"+
    "\107\54\271\0\71\54\7\0\37\54\1\0\12\22\146\0"+
    "\36\54\22\0\60\54\20\0\4\54\14\0\12\22\11\0"+
    "\25\54\5\0\23\54\260\0\40\30\40\35\200\0\113\54"+
    "\5\0\1\54\102\0\15\54\100\0\2\54\1\0\1\54"+
    "\34\0\370\54\10\0\363\54\15\0\37\54\61\0\3\54"+
    "\21\0\4\54\10\0\u018c\54\4\0\153\54\5\0\15\54"+
    "\3\0\11\54\7\0\12\54\146\0\32\30\32\35\32\30"+
    "\7\35\1\0\22\35\32\30\32\35\1\30\1\0\2\30"+
    "\2\0\1\30\2\0\2\30\2\0\4\30\1\0\10\30"+
    "\4\35\1\0\1\35\1\0\7\35\1\0\13\35\32\30"+
    "\32\35\2\30\1\0\4\30\2\0\10\30\1\0\7\30"+
    "\1\0\32\35\2\30\1\0\4\30\1\0\5\30\1\0"+
    "\1\30\3\0\7\30\1\0\32\35\32\30\32\35\32\30"+
    "\32\35\32\30\32\35\32\30\32\35\32\30\32\35\32\30"+
    "\34\35\2\0\31\30\1\0\31\35\1\0\6\35\31\30"+
    "\1\0\31\35\1\0\6\35\31\30\1\0\31\35\1\0"+
    "\6\35\31\30\1\0\31\35\1\0\6\35\31\30\1\0"+
    "\31\35\1\0\6\35\1\30\1\35\2\0\62\22\55\54"+
    "\12\0\7\54\2\0\12\22\4\0\1\54\u0171\0\54\54"+
    "\4\0\12\22\6\0\305\54\73\0\42\30\42\35\7\0"+
    "\1\54\4\0\12\22\246\0\4\54\1\0\33\54\1\0"+
    "\2\54\1\0\1\54\2\0\1\54\1\0\12\54\1\0"+
    "\4\54\1\0\1\54\1\0\1\54\6\0\1\54\4\0"+
    "\1\54\1\0\1\54\1\0\1\54\1\0\3\54\1\0"+
    "\2\54\1\0\1\54\2\0\1\54\1\0\1\54\1\0"+
    "\1\54\1\0\1\54\1\0\1\54\1\0\2\54\1\0"+
    "\1\54\2\0\4\54\1\0\7\54\1\0\4\54\1\0"+
    "\4\54\1\0\1\54\1\0\12\54\1\0\21\54\5\0"+
    "\3\54\1\0\5\54\1\0\21\54\164\0\32\56\6\0"+
    "\32\56\6\0\32\56\166\0\327\54\51\0\65\54\13\0"+
    "\336\54\2\0\u0182\54\16\0\u0131\54\37\0\36\54\342\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[28928];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\2\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\11\27\1\30\1\31\1\1\1\2\1\32\1\33\1\0"+
    "\1\34\1\35\1\0\1\36\1\37\1\40\1\41\3\27"+
    "\1\42\6\27\1\43\1\44\2\1\4\27\1\45\5\27"+
    "\1\46\1\47\1\27\1\50\1\27\1\51\1\27\1\52"+
    "\1\27\1\53\2\27\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\136\0\215\0\274\0\136\0\353"+
    "\0\u011a\0\136\0\136\0\136\0\136\0\136\0\136\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\136\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\136\0\136\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\u0439\0\136\0\136\0\u0468\0\u0497\0\136"+
    "\0\136\0\u04c6\0\u0149\0\136\0\u04f5\0\136\0\136\0\136"+
    "\0\136\0\u0524\0\u0553\0\u0582\0\u02c1\0\u05b1\0\u05e0\0\u060f"+
    "\0\u063e\0\u066d\0\u069c\0\136\0\136\0\136\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0787\0\u02c1\0\u07b6\0\u07e5\0\u0814\0\u0843"+
    "\0\u0872\0\u02c1\0\u02c1\0\u08a1\0\u02c1\0\u08d0\0\u02c1\0\u08ff"+
    "\0\u02c1\0\u092e\0\u02c1\0\u095d\0\u098c\0\u02c1\0\u02c1";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\3\2\33\1\34\1\35\1\36\1\37"+
    "\1\33\1\40\1\41\1\42\1\33\1\43\2\33\1\44"+
    "\1\45\1\3\1\33\1\30\14\46\1\47\4\46\1\3"+
    "\35\46\61\0\1\4\102\0\1\50\40\0\1\51\76\0"+
    "\1\52\3\0\16\52\3\0\2\52\22\0\1\53\50\0"+
    "\1\54\4\0\1\55\55\0\1\53\1\0\1\22\57\0"+
    "\1\56\61\0\1\57\56\0\1\60\56\0\1\61\52\0"+
    "\1\30\5\0\1\30\2\0\17\30\2\0\1\30\24\0"+
    "\1\33\5\0\1\33\2\0\17\33\3\0\2\33\22\0"+
    "\1\33\5\0\1\33\2\0\1\33\1\62\15\33\3\0"+
    "\2\33\22\0\1\33\5\0\1\33\2\0\7\33\1\63"+
    "\7\33\3\0\2\33\22\0\1\33\5\0\1\33\2\0"+
    "\1\33\1\64\15\33\3\0\2\33\22\0\1\33\5\0"+
    "\1\33\2\0\5\33\1\65\6\33\1\66\2\33\3\0"+
    "\2\33\22\0\1\33\5\0\1\33\2\0\4\33\1\67"+
    "\10\33\1\70\1\33\3\0\2\33\22\0\1\33\5\0"+
    "\1\33\2\0\12\33\1\71\4\33\3\0\2\33\22\0"+
    "\1\33\5\0\1\33\2\0\4\33\1\72\12\33\3\0"+
    "\2\33\22\0\1\33\5\0\1\33\2\0\12\33\1\73"+
    "\4\33\3\0\2\33\14\46\1\0\4\46\1\0\35\46"+
    "\21\0\1\74\46\0\1\75\45\0\2\55\1\76\2\0"+
    "\1\77\51\55\22\0\1\33\5\0\1\33\2\0\14\33"+
    "\1\100\2\33\3\0\2\33\22\0\1\33\5\0\1\33"+
    "\2\0\13\33\1\101\3\33\3\0\2\33\22\0\1\33"+
    "\5\0\1\33\2\0\7\33\1\102\7\33\3\0\2\33"+
    "\22\0\1\33\5\0\1\33\2\0\4\33\1\103\12\33"+
    "\3\0\2\33\22\0\1\33\5\0\1\33\2\0\16\33"+
    "\1\104\3\0\2\33\22\0\1\33\5\0\1\33\2\0"+
    "\7\33\1\105\7\33\3\0\2\33\22\0\1\33\5\0"+
    "\1\33\2\0\6\33\1\106\10\33\3\0\2\33\22\0"+
    "\1\33\5\0\1\33\2\0\1\33\1\107\12\33\1\110"+
    "\2\33\3\0\2\33\22\0\1\33\5\0\1\33\2\0"+
    "\15\33\1\111\1\33\3\0\2\33\2\0\1\76\76\0"+
    "\1\33\5\0\1\33\2\0\1\33\1\112\15\33\3\0"+
    "\2\33\22\0\1\33\5\0\1\33\2\0\4\33\1\113"+
    "\12\33\3\0\2\33\22\0\1\33\5\0\1\33\2\0"+
    "\13\33\1\111\3\33\3\0\2\33\22\0\1\33\5\0"+
    "\1\33\2\0\12\33\1\114\4\33\3\0\2\33\22\0"+
    "\1\33\5\0\1\33\2\0\7\33\1\115\7\33\3\0"+
    "\2\33\22\0\1\33\5\0\1\33\2\0\10\33\1\116"+
    "\6\33\3\0\2\33\22\0\1\33\5\0\1\33\2\0"+
    "\3\33\1\117\13\33\3\0\2\33\22\0\1\33\5\0"+
    "\1\33\2\0\15\33\1\120\1\33\3\0\2\33\22\0"+
    "\1\33\5\0\1\33\2\0\4\33\1\121\12\33\3\0"+
    "\2\33\22\0\1\33\5\0\1\33\2\0\1\33\1\122"+
    "\15\33\3\0\2\33\22\0\1\33\5\0\1\33\2\0"+
    "\14\33\1\123\2\33\3\0\2\33\22\0\1\33\5\0"+
    "\1\33\2\0\12\33\1\124\4\33\3\0\2\33\22\0"+
    "\1\33\5\0\1\33\2\0\14\33\1\125\2\33\3\0"+
    "\2\33\22\0\1\33\5\0\1\33\2\0\10\33\1\126"+
    "\6\33\3\0\2\33\22\0\1\33\5\0\1\33\2\0"+
    "\4\33\1\127\12\33\3\0\2\33";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2491];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\2\11\2\1\1\11\2\1\6\11\4\1"+
    "\1\11\4\1\2\11\11\1\2\11\2\1\2\11\1\0"+
    "\1\1\1\11\1\0\4\11\12\1\3\11\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[87];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
	private Symbol newToken(short id)
	{
		return new Symbol(id, yyline + 1, yycolumn + 1, yylength());
	}

	private Symbol newToken(short id, Object value)
	{
		return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MiniLangLex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	return newToken(Terminals.EOF, "end-of-file");
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 46: break;
          case 2:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
            // fall through
          case 47: break;
          case 3:
            { /* Não faz nada  */
            }
            // fall through
          case 48: break;
          case 4:
            { return newToken(Terminals.NOT);
            }
            // fall through
          case 49: break;
          case 5:
            { return newToken(Terminals.MOD);
            }
            // fall through
          case 50: break;
          case 6:
            { return newToken(Terminals.AP);
            }
            // fall through
          case 51: break;
          case 7:
            { return newToken(Terminals.FP);
            }
            // fall through
          case 52: break;
          case 8:
            { return newToken(Terminals.MULT);
            }
            // fall through
          case 53: break;
          case 9:
            { return newToken(Terminals.PLUS);
            }
            // fall through
          case 54: break;
          case 10:
            { return newToken(Terminals.COMMA);
            }
            // fall through
          case 55: break;
          case 11:
            { return newToken(Terminals.SUB);
            }
            // fall through
          case 56: break;
          case 12:
            { return newToken(Terminals.DOT);
            }
            // fall through
          case 57: break;
          case 13:
            { return newToken(Terminals.DIV);
            }
            // fall through
          case 58: break;
          case 14:
            { return newToken(Terminals.INT, Integer.parseInt(yytext()) );
            }
            // fall through
          case 59: break;
          case 15:
            { return newToken(Terminals.COLON);
            }
            // fall through
          case 60: break;
          case 16:
            { return newToken(Terminals.SEMI);
            }
            // fall through
          case 61: break;
          case 17:
            { return newToken(Terminals.LESSER);
            }
            // fall through
          case 62: break;
          case 18:
            { return newToken(Terminals.EQ);
            }
            // fall through
          case 63: break;
          case 19:
            { return newToken(Terminals.GREATER);
            }
            // fall through
          case 64: break;
          case 20:
            { return newToken(Terminals.TYPE, yytext());
            }
            // fall through
          case 65: break;
          case 21:
            { return newToken(Terminals.LB);
            }
            // fall through
          case 66: break;
          case 22:
            { return newToken(Terminals.RB);
            }
            // fall through
          case 67: break;
          case 23:
            { return newToken(Terminals.ID, yytext());
            }
            // fall through
          case 68: break;
          case 24:
            { return newToken(Terminals.AC);
            }
            // fall through
          case 69: break;
          case 25:
            { return newToken(Terminals.FC);
            }
            // fall through
          case 70: break;
          case 26:
            { return newToken(Terminals.DIF);
            }
            // fall through
          case 71: break;
          case 27:
            { return newToken(Terminals.AND);
            }
            // fall through
          case 72: break;
          case 28:
            { return newToken(Terminals.FLOAT, Float.parseFloat(yytext()) );
            }
            // fall through
          case 73: break;
          case 29:
            { yybegin(COMMENT);
            }
            // fall through
          case 74: break;
          case 30:
            { return newToken(Terminals.DBCOLON);
            }
            // fall through
          case 75: break;
          case 31:
            { return newToken(Terminals.LESSEREQUAL);
            }
            // fall through
          case 76: break;
          case 32:
            { return newToken(Terminals.EQUALTO);
            }
            // fall through
          case 77: break;
          case 33:
            { return newToken(Terminals.GREATEREQUAL);
            }
            // fall through
          case 78: break;
          case 34:
            { return newToken(Terminals.IF);
            }
            // fall through
          case 79: break;
          case 35:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 80: break;
          case 36:
            { return newToken(Terminals.CHAR, yytext().charAt(1));
            }
            // fall through
          case 81: break;
          case 37:
            { return newToken(Terminals.NEW);
            }
            // fall through
          case 82: break;
          case 38:
            { return newToken(Terminals.DATA);
            }
            // fall through
          case 83: break;
          case 39:
            { return newToken(Terminals.ELSE);
            }
            // fall through
          case 84: break;
          case 40:
            { return newToken(Terminals.NULL, null);
            }
            // fall through
          case 85: break;
          case 41:
            { return newToken(Terminals.READ);
            }
            // fall through
          case 86: break;
          case 42:
            { return newToken(Terminals.BOOL, Boolean.parseBoolean(yytext()));
            }
            // fall through
          case 87: break;
          case 43:
            { return newToken(Terminals.PRINT);
            }
            // fall through
          case 88: break;
          case 44:
            { return newToken(Terminals.RETURN);
            }
            // fall through
          case 89: break;
          case 45:
            { return newToken(Terminals.ITERATE);
            }
            // fall through
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
